# Generated by Django 3.2.25 on 2026-05-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canchas', '0002_deportes_iniciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='capacidad',
            field=models.IntegerField(default=10, verbose_name='Capacidad'),
        ),
        migrations.AddField(
            model_name='cancha',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, verbose_name='Dirección'),
        ),
    ]
